name: main

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  imagetag: ${{ github.head_ref || github.ref_name || 'dev' || 'main'}}
  branch: ${{ github.head_ref || github.ref_name || 'dev' || 'main'}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: dump values
        run: |
          echo "ghcr.io/abcdesktopio/mongo:${{ env.imagetag }}"
          echo "branch:${{ env.branch }}"

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          context: .
          file: Dockerfile
          push: false
          build-args: |
            branch:${{ env.branch }}
          tags: |
            ghcr.io/jfv-orange/test-template:safe${{ env.imagetag }}